### ISSUE TITLE
Possible interface for Perl <-> FFI - Inline?

### ISSUE THREAD

**Issue by mohawk2** [plicease-legacy/Alien-Install#2]
Saw your talk on libarchive via FFI, thought it was extremely interesting. I have managed to get ExtUtils::Depends and Inline to work together fairly closely (with EU::D 0.400, released today), such that an XS module can allow other Perl code to `use Inline with => 'ModuleName'` and it'll just work, if the XS module uses EU::D in its EUMM install process.

What occurred to me when I saw your talk, and is now a bit more realisable thanks to the above, is the Inline would provide a possible interface to enabling FFI. It already:
- generates XS
- builds it
- loads the DLL
- binds the found C functions to Perl functions

It seems to me FFI would benefit from, and only need, points 3 and 4 from this. In addition, [`Inline::Struct`](https://metacpan.org/pod/Inline::Struct) provides a fairly neat interface between a Perl object and a C struct, which I recall you mentioning as an issue in your talk.

`Inline` already has a method for making a Perl module distribution, in a similar spirit to h2xs. Do you agree this is a way forward to achieve good Perl FFI?

**Comment by plicease** [comment]
My one concern is that things like `Inline::Struct` use (correct me if I am wrong) use XS under the covers, and my goal (I can dream yeah?) is to make the XS layer so small that it can be replaced by something better or implemented differently for alternate implementations of Perl 5.  Still I like the idea of offering alternatives to directly writing XS.  This is the main reason I mentioned `Inline::Struct` as an interesting exercise but haven't actually done it myself.

Do you have a project in mind?  I might be interested in collaborating or at least coordinating :)

**Comment by mohawk2** [comment]
Yes, Inline::Struct is currently implemented using all 4 steps mentioned above, but I don't see a fundamental reason why it couldn't also do the "pack" thing without XS.

I very much do have a project in mind! For want of a better name, how about Inline::FFI? And Inline::Struct::FFI.

**Comment by plicease** [comment]
Cleaning up old issues, I believe `Alien::Base` and `FFI::Platypus` address some of these issues.  May revisit this if development on `Alien::Install` ever ramps up again.  Right now, that is not looking likely.
